# Target-Guided Ordinal Encoding (Definition):

Target-Guided Ordinal Encoding is a technique used in machine learning to convert categorical variables into numerical values by using the target variable (output) to determine the order of categories.

🔑 Simple Definition:

It assigns a rank (order) to each category based on the mean (or another statistic) of the target variable for that category.

In [29]:
import pandas as pd

#create a sample dataframe with categorical variable and target variable
df = pd.DataFrame({
    'city':['New York' ,'London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [30]:
df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180

In [31]:
## calculate mean price of each city
mean_price =df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [32]:
## replace each city with its mean price
df['city_encoded']=df['city'].map(mean_price)

In [33]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [34]:
import seaborn as sns

In [35]:
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## Nominal /One Hot Encoding Techniques

#Nominal One-Hot Encoding is a technique used in machine learning to convert nominal categorical data (categories with no natural order) into numerical format by creating separate binary columns (0 or 1) for each category.

# disadvantages
1.create sparse matrix[overfitting]
2.it will increase the no of features

In [36]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [37]:
#cretae a sample dataframe with categorical variable
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [38]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [39]:
## create an instance of one hot encoder
encoder = OneHotEncoder()

In [40]:
#fit the encoder to the dataframe and transform the categorical variable
encoded = encoder.fit_transform(df[["color"]])

In [41]:
encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [42]:
import pandas as pd
encoded_df = pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [43]:
encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red'], dtype=object)

In [44]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [45]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [46]:
import seaborn as sns

In [47]:
sns.load_dataset('tips') #practice purpose

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

#Label Encoding (Ordinal Encoder) – Definition

Label Encoding (also called Ordinal Encoding) is a technique used in machine learning to convert categorical data (text labels) into numerical values by assigning each unique category a number.

🔹 Simple Definition:

Label/Ordinal Encoding transforms categories into numbers like:

Category → Number

## Label Encoder

In [48]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [49]:
#cretae a sample dataframe with categorical variable
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [50]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [51]:
## create instance of LabelEncoder
encoder = LabelEncoder()

In [52]:
encoder.fit_transform(df['color'])

array([2, 0, 1, 1, 2, 0])

## Ordinal Encoding

In [53]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

#create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [54]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [55]:
# create an instance of the ordinalencoder class and fit transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [56]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])